Features/#26
cbnu-sequence/proreviewer-backend pull request #90
Opened 2022-11-02 03:50 UTC by mk3058

## 이슈 번호
- #26 
## 작업 설명
post CRUD와 검색 기능을 추가했습니다.

2022-11-02 04:56 UTC, ckyeon requested changes

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/controller/PostRestController.java
> +public class PostRestController {
클래스의 이름을 `PostRestController` -> `PostController`로 바꾸는게 좋아보입니다.
이미 `@RestController` 애노테이션이 `RestController`임을 나타내기 때문입니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/controller/PostRestController.java
> +    @GetMapping//모든 포스트 조회
주석은 굳이 필요 없어보입니다~

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +    private String userName;
아래에 user와의 연관관계 매핑이 있기 때문에 해당 variable은 필요하지 않을 것 같아용

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +    @JoinColumn(name = "userId")
`@JoinColumn`의 name에는 카멜 케이스가 아니라 스네이크 케이스를 사용합니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +}
intelliJ의 코드 정렬 기능을 이용해서 형식을 조정하는게 좋을 것 같습니다.
코드 정렬 단축키: `opt` + `cmd` + `L`

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/dto/PostUpdateDto.java
> +    public PostUpdateDto(String title, String body, String email){
email 파라미터는 사용하지 않는 것 같습니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/infra/repository/jpa/impl/PostRepositoryImpl.java
> +
이미 `PostRepository`이기 때문에 메소드의 뒤에 Post를 붙일 필요가 없을 것 같아용

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/infra/repository/jpa/impl/PostRepositoryImpl.java
> +    }
한 라인에 `.`이 두 개 이상 들어가지 않게 변수로 쪼개는 것이 좋아보입니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +        User user = userRepository.findById(postRequestDto.getUser_id()).orElseThrow(UserNotFoundException::new); //작성자 정보
한 라인에 `.`이 두 개 이상 들어가지 않게 변수로 쪼개는 것이 좋아보입니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +@AllArgsConstructor
`@RequiredArgsConstructor`가 적절해 보입니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +        Post post = postRepository.findById(id).orElseThrow(PostNotFoundException::new);
한 라인에 `.`이 두 개 이상 들어가지 않게 변수로 쪼개는 것이 좋아보입니다.

2022-11-02 04:56 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +    public List<PostResponseDto> searchPost(int type, String keyword){
`type`의 의미를 추측할 수 있도록 enum을 이용하고,
아래의 조건문들은 추상화하여 중복된 부분을 제거할 수 있으면 좋겠습니다.

2022-11-02 05:19 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/controller/PostRestController.java
> +public class PostRestController {
PostController 로 수정하는게 더 좋겠네요! 감사합니다

2022-11-02 05:34 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +        Post post = postRepository.findById(id).orElseThrow(PostNotFoundException::new);
findById 의 결과를 Optional<Post> 변수로 받고 아래에서 따로 get 해주는 방식이 좋을까요?

2022-11-02 05:34 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +@AllArgsConstructor
수정하겠습니다!

2022-11-02 05:35 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/dto/PostUpdateDto.java
> +    public PostUpdateDto(String title, String body, String email){
앗 구조를 바꾸면서 빼먹었네요 삭제하겠습니다.

2022-11-02 05:36 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/controller/PostRestController.java
> +    @GetMapping//모든 포스트 조회
주석 삭제하겠습니다.

2022-11-02 05:37 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +    private String userName;
맞습니다 삭제하겠습니다!!

2022-11-02 05:37 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +    @JoinColumn(name = "userId")
확인했습니다! 수정하겠습니다

2022-11-02 06:02 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +        Post post = postRepository.findById(id).orElseThrow(PostNotFoundException::new);
엇 해당 코멘트는 잘못 달았습니다 ㅎ..

2022-11-03 00:08 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/infra/repository/jpa/impl/PostRepositoryImpl.java
> +
수정했습니다!

2022-11-03 00:09 UTC, mk3058 commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +}
정렬 수정했습니다

2022-11-03 06:14 UTC, ckyeon requested changes

2022-11-03 06:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/common/searchType/SearchType.java
> +    title, body, author
enum의 멤버는 대문자로 작성하는 것이 옳습니다~

2022-11-03 06:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/infra/repository/jpa/impl/PostRepositoryImpl.java
> +    }
`findById()`와 `orElseThrow`를 추가적으로 쪼갤 수 있을 것 같습니다

2022-11-03 06:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/infra/repository/jpa/impl/PostRepositoryImpl.java
> +        postRepository.delete(post);
spring data jpa에서 기본적으로 지원해주는 `deleteById()` 메소드도 있으니 알아두시면 좋을 것 같아용~

2022-11-03 06:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +        User user = userRepository.findById(user_id).orElseThrow(UserNotFoundException::new); //작성자 정보
해당 부분도 `findById()`와 `orElseThrow()`부분을 쪼갤 수 있을 것 같습니다.

2022-11-03 06:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +        try (Stream<Post> postStream = postRepository.getAll()) {
메소드의 이름을 `findAll()`로 바꾸어 다른 메소드와 컨벤션을 맞추는 것이 좋아보입니다.

2022-11-03 06:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/service/PostService.java
> +                    postRepository.delete(id);
메소드의 이름을 `deleteById()`로 변경하여 어떤 매개변수를 이용해 포스트를 삭제하는지 명시해주는 것이 좋아보입니다.

2022-11-03 11:42 UTC, ckyeon requested changes

2022-11-03 11:42 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/domain/Post.java
> +    User user;
`private` 접근 제어자를 달아주시는게 좋아 보여용

2022-11-03 11:42 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/dto/PostRequestDto.java
> +    private Long user_id;
dto를 통해 `user_id`를 받아오지 않고, spring security를 통해 받아올 예정입니다.
또한, 카멜 케이스를 지켜주세용

2022-12-30 13:14 UTC, ckyeon requested changes

2022-12-30 13:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/controller/PostController.java
> +    public List<PostResponseDto> getAllPosts() {
`findAll()`이 더 적합해보입니다!

2022-12-30 13:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/controller/PostController.java
> +}
`PostController`이기 때문에 각 메소드의 이름에 Post를 붙힐 필요가 없어 보입니다!

2023-01-01 18:44 UTC, ckyeon approved these changes

2023-01-01 18:44 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/dto/PostResponseDto.java
> +    }
매개변수가 하나이기 때문에 builder 패턴을 쓰기 보다는
아래와 같이 static 메소드를 만드는 것이 좋아보입니다!

### 예시
```java
@Getter
public class FindAllResponseDto {

    private Long id;
    private String email;
    private String name;

    private FindAllResponseDto(Long id, String email, String name) {
        this.id = id;
        this.email = email;
        this.name = name;
    }

    public static FindAllResponseDto fromEntity(User user) {
        return new FindAllResponseDto(
                user.getId(),
                user.getEmail(),
                user.getDescription()
        );
    }
}

```

2023-01-03 03:14 UTC, ckyeon commented on src/main/java/com/sequence/proreviewer/post/dto/PostResponseDto.java
> +    }
[이펙티브 자바 아이템 2](https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-2.-%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90-%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EA%B0%80-%EB%A7%8E%EB%8B%A4%EB%A9%B4-%EB%B9%8C%EB%8D%94%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC)
이펙티브 자바에서도 생성자에 매개변수가 많은 경우 빌더를 사용하는 것을 추천하고 있습니다!

2023-01-12 06:19 UTC, ckyeon approved these changes
LGTM 👍

2023-01-16 06:42 UTC, merged